# Generated by Django 5.0.2 on 2025-05-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0006_alter_alumnos_curp_alter_maestros_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
